# Generated by Django 2.1.7 on 2019-03-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dob',
            field=models.DateField(),
        ),
    ]
