# Generated by Django 2.1.7 on 2019-04-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0003_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Formulario.Persona'),
        ),
    ]
